### ISSUE TITLE
Handle shopping cart with CRUD operations

### ISSUE THREAD

**Issue by AndreaGiuntiniUNIFI** [APTUnifi/OnlineShopSimulator#15]
We should be able to perform operations like add, view and remove of the shopping cart

**Comment by andreagemelli** [comment]
SQL methods implemented. We should also:

- implement MongoDB side

- refactor the code at the end together

**Comment by AndreaGiuntiniUNIFI** [comment]
Found out the last error build.
In the item class we had to remove the quantity comparison within the equals overridden method.

**Comment by AndreaGiuntiniUNIFI** [comment]
All repository tests and methods finished, we still need to :
- refactor some methods name
- be sure that equals method for cart is correct

**Comment by andreagemelli** [comment]
Perfect. We will implements the remaining points in the next issues.
